name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g html-minifier-terser
        npm install -g clean-css-cli
        npm install -g uglify-js

    - name: Create and populate dist folder
      run: |
        mkdir -p dist
        cp *.html dist/
        cp *.css dist/
        cp *.js dist/

    - name: Minify files
      run: |
        html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true --input-dir ./dist --output-dir ./dist --file-ext html
        for file in dist/*.css; do cleancss -o "${file%.css}.min.css" "$file"; done
        for file in dist/*.js; do uglifyjs "$file" -o "${file%.js}.min.js"; done
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: khalidalghifarii/popl-kelompok7-kalkulatorbmi:latest
