name: CI/CD Pipeline for HTML/CSS/JS Project

# Workflow ini akan berjalan setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment (optional, useful if you have npm scripts or use tools like webpack)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Atur versi node sesuai kebutuhan, jika tidak diperlukan bisa dihapus

      # Install dependencies (Jika ada package.json, hapus jika tidak menggunakan npm)
      - name: Install dependencies
        run: npm install

      # Build the project (optional, untuk proyek static seperti HTML/CSS/JS ini bisa dihilangkan jika tidak ada proses build)
      - name: Build project
        run: npm run build  # Hapus atau sesuaikan jika tidak ada proses build

      # Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: khalidalghifarii/kalkulatorbmi_kelompok7_popl:latest

      # (Optional) Deploy to server or other steps if necessary
